version: "3.9"

services:
  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx_reverse_proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./volumes/logs:/var/log/nginx
  #     - ./proxy_params.conf:/etc/nginx/proxy_params.conf
  #     - /etc/letsencrypt:/etc/letsencrypt
  #   depends_on:
  #     - server

  postgres:
    container_name: server-postgres
    image: postgres:14
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: ubuntu
      POSTGRES_DB: postgresDB
      TZ: America/New_York
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

  server:
    container_name: server-api
    build:
      context: .
    image: vote-server-img
    environment:
      TZ: America/New_York
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./volumes/logs
        target: /server/volumes/logs
      - type: bind
        source: ./volumes
        target: /server/volumes
